---
- name: sectes test from environment variables
on:
  workflow_dispatch:
jobs:
  secrets_testing:
    runs-on: ubuntu-latest
    environment: DEV

    steps:
      - name: retrieve secrets from env DEV
        run: echo "Using Secret"
        env:
          DB_PASSWORD: ${{ secrets.DEV_SECRET1 }}
          DB_PASSWORD1: ${{ secrets.DEV_SECRET2 }}
          DB_username: ${{ vars.DEV_VAR1 }}
          DB_username2: ${{ vars.DEV_VAR2 }}
          
          
          
